# Generated by Django 5.0.6 on 2024-07-02 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_category_options_alter_post_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='tag_name')),
                ('posts', models.ManyToManyField(related_name='tags', to='blog.post', verbose_name='posts')),
            ],
        ),
    ]
