# Generated by Django 5.0.6 on 2024-07-10 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_tag_posts_post_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.URLField(default='http://placehold.it/64x64', verbose_name='user_avatar')),
                ('username', models.CharField(max_length=50, verbose_name='comment_usernane')),
                ('publish_date', models.DateTimeField(auto_now_add=True, verbose_name='publish_date')),
                ('content', models.TextField(verbose_name='comment_content')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.post')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
    ]
