# Generated by Django 5.0.6 on 2024-07-10 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='username',
            field=models.CharField(default='username', max_length=50, verbose_name='comment_usernane'),
        ),
    ]
