# Generated by Django 5.0.6 on 2024-07-10 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_comment_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='username',
            field=models.CharField(default='username', max_length=50, verbose_name='usernane'),
        ),
    ]
