# Generated by Django 5.0.6 on 2024-07-18 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_userprofile_delete_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
