# Generated by Django 5.0.6 on 2024-07-21 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='username',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(default='No bio provided', verbose_name='About Me'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='country',
            field=models.CharField(default='Ukraine', max_length=30, verbose_name='Country'),
        ),
    ]
