# Generated by Django 5.0.6 on 2024-07-21 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_userprofile_options_comment_user_post_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='http://placehold.it/900x300', upload_to='photos', verbose_name='image'),
        ),
    ]
