# Generated by Django 5.0.7 on 2024-07-22 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_comment_last_modified_post_last_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='last_modified'),
        ),
    ]
