# Generated by Django 5.0.7 on 2024-07-22 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_alter_post_publish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='last_modified',
            field=models.DateTimeField(auto_created=True, null=True, verbose_name='last_modified'),
        ),
        migrations.AlterField(
            model_name='post',
            name='last_modified',
            field=models.DateTimeField(auto_created=True, blank=True, null=True, verbose_name='last_modified'),
        ),
    ]
