# Generated by Django 5.0.7 on 2024-07-22 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='first_post_image',
            field=models.ImageField(blank=True, null=True, upload_to='photos', verbose_name='First Post Image'),
        ),
        migrations.AddField(
            model_name='post',
            name='second_post_image',
            field=models.ImageField(blank=True, null=True, upload_to='photos', verbose_name='Second Post Image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photos', verbose_name='Preview image'),
        ),
    ]
